### ISSUE TITLE
No admin user

### ISSUE THREAD

**Issue by jlnbdt** [YunoHost-Apps/wekan_ynh#64]
Hi,

After a fresh install of Wekan, it seems that the first user logged in is not admin, contrary to what should happen. So I can't access admin panel.

Have a nice day.

**Comment by yalh76** [comment]
As LDAP authentification is enable by default, wekan admins are the members of the YunoHost LDAP admin group. To add an account in the YunoHost, you must first install phpLDAPadmin , connect to the interface and in the left panel go on dc=yunohost,dc=org, ou=groups, cn=admins. In the right panel, in the memberUid category, click on modify group members, add the account in the group, save changes and update object

If you have disable ldap authentication, first registered user will be admin, and next ones normal users. If you want other admins too, you can change their permission to admin at Wekan Admin Panel.

**Comment by jlnbdt** [comment]
Thanks for these very clear explanations! 👍 
I can now access admin panel 😄

**Comment by bombyy** [comment]
Hey, I see that this question is closed but I can't seem to get the answer working.
I installed Wekan and I logged in via LDAP with the user that  I installed Wekan with. After I logged in I couldn't find the Admin Panel so ich checked the Permissions and my user has the Wekan (Admin) Permissions in yunohost.
I found this post but I'm having problms with phpldapadmin (I can only login Anonymously) but imo I should be able to use admin settings when I have the Wekan (Admin) Permissions.

**Comment by lauhub** [comment]
Did someone find a solution ? I actually experience the same problem with a fresh Yunohost/Wekan installation.

**Comment by lauhub** [comment]
Here is the output of `yunohost user permission list`:

```
permissions: 
  mail.main: 
    allowed: all_users
  phpldapadmin.main: 
    allowed: admins
  sftp.main: 
    allowed: 
  ssh.main: 
    allowed: 
  wekan.main: 
    allowed: 
      - all_users
      - mygroup01
  xmpp.main: 
    allowed: all_users
```

The `wekan.admin` permission is missing, obviously. How to add/create it ?
