### ISSUE TITLE
Warning during backup : "The service wekan didn't fully started before the timeout."

### ISSUE THREAD

**Issue by SiM** [YunoHost-Apps/wekan_ynh#77]
Hi,

When backuping Wekan (`yunohost backup create --apps wekan`), I have almost every time a warning about  _"The service wekan didn't fully started before the timeout."_ caused by a LDAP Background Sync error (regarding the log provided)

But the service still launches, despite this message.

Here is the full log : 
https://paste.yunohost.org/hijiqinufe.vbs

```
# yunohost --version
yunohost:
  repo: stable
  version: 3.6.5.3
yunohost-admin:
  repo: stable
  version: 3.6.5.1
moulinette:
  repo: stable
  version: 3.6.4.1
ssowat:
  repo: stable
  version: 3.6.4

#  yunohost app info wekan
description: Trello-like kanban
license: MIT
name: Wekan
version: 3.55~ynh1
```

**Comment by yalh76** [comment]
I made some test to the version 3.55~ynh1 without encountering that issue. 
Maybe you should upgrade first to actual wekan version => 3.79~ynh1

**Comment by SiM** [comment]
Hi, sorry for the delay in responding.

Despite upgrading wekan, I have still the same error (but not the same log), this time with every backup.

See the log here : https://paste.yunohost.org/ijoxaxeyup.vbs 
It is the last user created on YNH that appears in the log (it changes to the last when creating a new one), no matter if the user has access to wekan or not, has already logged in wekan or not (I have tested these cases).

```
# yunohost --version
yunohost:
  repo: stable
  version: 3.7.0.12
yunohost-admin:
  repo: now
  version: 3.7.0.3
moulinette:
  repo: stable
  version: 3.7.0.2
ssowat:
  repo: stable
  version: 3.7.0.3
```

```
# yunohost app info wekan
description: Trello-like kanban
license: MIT
name: Wekan
version: 3.79~ynh1
```
